spring.application.name=Clientes

spring.datasource.url=jdbc:mysql://98.88.164.104:3306/Perfulandia
spring.datasource.username=perfume
spring.datasource.password=perfume123

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

Droptable.enabled=false

server.port=8084


##    {
##    "primerNombre": "Sofía",
##   "ultimoNombre": "Gutiérrez",
##    "correoElectronico": "sofia.guti@softwaremail.net",
##    "calle": "Calle de los Algoritmos 10",
##    "ciudad": "Tecnolópolis",
##    "pais": "Digitalia",
##    "codigoPostal": "01001"
##    }
