spring.application.name=perfulandia

spring.datasource.url=jdbc:mysql://98.90.230.159:3306/perfulandia
spring.datasource.username=perfume
spring.datasource.password=perfume123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


server.port=8084