spring.application.name=Clientes

spring.datasource.url=jdbc:mysql://98.88.164.104:3306/Perfulandia
spring.datasource.username=perfume
spring.datasource.password=perfume123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

Droptable.enabled=false

server.port=8080